export const FetchProducts = 'FETCH_PRODUCTS'
export const FetchCart = 'FETCH_CART'
export const AddToCart = 'ADD_TO_CART'
export const UpdateCart = 'UPDATE_CART'
export const EmptyCart = 'EMPTY_CART'
export const RemoveCartProduct = 'REMOVE_CART_PRODUCT'
export const FetchCountries = 'FETCH_COUNTRIES'
export const GetToken = 'GET_TOKEN'
export const SetShippingCountry = 'SET_SHIPPING_COUNTRY'
export const SetShippingSubdivision = 'Set_Shipping_Subdivision'
export const SetShippingOption = 'Set_Shipping_Option'
export const FetchShippingSubdivisions = 'Fetch_Shipping_Subdivisions'
export const FetchShippingOptions = 'Fetch_Shipping_Options'
export const SetShippingData = 'Set_Shipping_Data'
export const SetIncomingOrder = 'SetIncomingOrder'
export const RefreshCart = 'RefreshCart'
export const SetErrorMessage = 'SetErrorMessage'

